### ISSUE TITLE
CRC calculation issue

### ISSUE THREAD

**Issue by Jansen-byte** [millerlp/MS5803_02#1]
Today I connected a MS5803-02BA to an arduino uno. I was glad to find this library to get it up and running very fast. 
The only issue I had was that I kept getting the "MS5803 CRC check FAILED!" error.
After some digging I noticed something strange;
"p_crc: 247
 n_crc: 7"
The received CRC was 247 according to the software, while:
`// The last 4 bits of the 7th coefficient form a CRC error checking code.` 
With only 4 bits, 247 could never be the CRC.
After modifiying the software to only take the last 4 bits, the CRC error is gone. 

Modification: 
Add on line 119 of MS5803_02.cpp: 
`p_crc &= 0b00001111; // Addition, only take last 4 bits of P_crc`

My apologies if this is not the proper way to address this, after plenty of lurking, this is my first submission on github.

**Comment by millerlp** [comment]
Thank you for catching that. I've added the suggested change.
